### ISSUE TITLE
Running the pertained sentiment model interactively per sentence

### ISSUE THREAD

**Issue by 12max34** [NVIDIA/sentiment-discovery#10]
Hi , 
Can you provide some hints or sample codes for running the pertained sentiment model to get output on a sentence?

**Comment by raulpuric** [comment]
Hi by interactive do you mean you want to run this to featurize individual sentences in your own python script.

Could you look at script visualize.py where we process a single sentence. 

It's a little bit clunky and there's some additional steps with the configure_usage part to create the model, but this visualize.py script should have what you need to process a single sentence to get the cell state and hidden_state needed for sentiment analysis. We're working on slimming down the additional code, but this will take a while.

Let us know if you're unable to find what you need in the script.

**Comment by 12max34** [comment]
Can you point to me the function that gets the sentiment score for a sentence?

**Comment by 12max34** [comment]
Hi @raulpuric any updates?

**Comment by raulpuric** [comment]
Ahh I see what you mean. 

The visualize.py file is used just to tag sentences with the activations of a particular neuron in order to feed them into a heatmap. The sentiment score is not the average of out_values.

In order to get sentiment analysis we use the model as a featurizer, taking the same activations used in the heatmap. and in the sentiment_transfer script we use extracted features and a sentiment benchmark dataset to learn a sentiment classifier that we can use to evaluate a PyTorch test dataset. The test dataset evaluation results are saved. The sentiment classifier weights are also saved and can be used at a later time in scripts. 

We do not however explicitly have a function to get the sentiment score of a sentence interactively from this model and the sentiment weights. I can have a script/example up later tonight/early tomorrow to do this.

**Comment by raulpuric** [comment]
Hi the classification script should look roughly like this. We'll include something more official in the coming days.

```
weights = Variable(torch.from_numpy(np.load(...)))
bias = Variable(torch.from_numpy(np.load(...)))
text_batch = ...

sigmoid_layer = torch.nn.Sigmoid()

init_state = (Variable(torch.zeros(batch_size, num_layers, hidden_size), requires_grad=False), Variable(torch.zeros(batch_size, num_layers, hidden_size), requires_grad=False))
states = init_state

for t in range(text_batch.size(1):
	e = embed(text_batch[:,t])
	states, output = rnn(e, states)
	if isinstance(states, tuple):
		hidden, cell = states
	else:
		hidden = cell = states

#take the last cell state and use for sentiment classification
sigmoid_layer(F.linear(cell, w, b))

```

Link to pretrained classification weights+bias https://drive.google.com/open?id=1kv0jOtuNjOGTfN3cgiYN_yUjj0hnfGe7

**Comment by 12max34** [comment]
Thanks @raulpuric for your code, although I figured out another way  - 

`import torch
from torch.autograd import Variable
from torch import optim
from torch.utils import data as td
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
from timeit import default_timer as timer
from sentiment_discovery.data_utils import loaders
from sentiment_discovery.data_utils.preprocess import process_str
# from sentiment_discovery import modules
import sentiment_discovery.neuron_transfer.utils as utils
from sentiment_discovery.neuron_transfer import transform
# from sentiment_discovery.model import run_model
from cfg import cfg, configure_usage

with open("sklearn_model_5.pkl","rb") as f:
      sklearn_model = pkl.load(f)
      print (sklearn_model)
print ('Loded Sklearn model..')      
configure_usage('sentiment_transfer.py')
opt = cfg.opt
model = cfg.model
print ('Loaded Sentiment Model..')


def run_interactive(text):
        text = process_str(text)
        processed_text = "\n %s "% text
        len_text = len(processed_text)
        teX = [(processed_text, 1, len_text)]
        s= timer()
        teX = loaders.DataLoader(teX)
        teXt = transform(model, teX, 1)
        e = timer()
        diff = e-s
        proba = sklearn_model.predict_proba(teXt)
        # print("Sentiment score and time : ",proba[0][1],diff)
        return proba[0][1],diff


if __name__ == '__main__':

    while True :
        text = input("Enter a sentence : \n")
        sentiment,time = run_interactive(text)
        print ("Sentiment score and time : ",sentiment,time)`

**Comment by raulpuric** [comment]
Yeah we're working on it. Thanks for your patience. This was just a sneak peek of what we've been working on. Stay tuned :)

**Comment by ibrahimsharaf** [comment]
Hi @12max34, can you add the script you've used here? (instead of the screenshot, for easier reproducibility)
