### ISSUE TITLE
What is BPC in the graphs in the readme?

### ISSUE THREAD

**Issue by rainjacket** [NVIDIA/sentiment-discovery#25]
Is it bits per character, is it therefore the base 2 log of ppl (perplexity per letter (?)) which is output by the training routine?

I'm hoping to clarify what all the numbers mean to make sure I am getting the expected results.

**Comment by raulpuric** [comment]
That’s correct.
The loss is currently in base e and you can get bpc by multiplying the loss by 1.44 to change from base e to base 2.
