### ISSUE TITLE
name 'cfg' is assigned to before global declaration

### ISSUE THREAD

**Issue by stefan-it** [NVIDIA/sentiment-discovery#3]
Hi,

thanks for providing an implementation of your work!

I would like to test the sentiment discovery on my own dataset, but unfortunately the following error message appears:

```bash
python3 text_reconstruction.py --help
  File "text_reconstruction.py", line 30
    global cfg
    ^
SyntaxError: name 'cfg' is assigned to before global declaration
```

It also appears when running the training command as documented in `README.md`. I'm using Python3. Please  let me know if you need further information!

Thanks,

Stefan

**Comment by raulpuric** [comment]
Ahhh, interesting. That only shows as a warning on our system. Will make the change shortly. Try again in an hour or two.

**Comment by raulpuric** [comment]
should be fixed

**Comment by stefan-it** [comment]
Thanks, the patch worked for me :)
