### ISSUE TITLE
Bug with read_csv

### ISSUE THREAD

**Issue by rlebret** [NVIDIA/sentiment-discovery#39]
Hi,
There is a minor bug when reading tsv files at those two lines:
- https://github.com/NVIDIA/sentiment-discovery/blob/master/data_utils/datasets.py#L139
- https://github.com/NVIDIA/sentiment-discovery/blob/master/data_utils/datasets.py#L141

`sep=delim` should be replaced by `sep=self.delim`

**Comment by raulpuric** [comment]
You're absolutely right. I just made the fix.

Thanks :)
