### ISSUE TITLE
cannot import name '_unflatten_tensors'

### ISSUE THREAD

**Issue by stefan-it** [NVIDIA/sentiment-discovery#4]
Hi,

 `data_parallel.py"` uses the following import from pytorch:

```python
from torch._utils import _unflatten_tensors
```

This function was recently removed with [this commit](https://github.com/pytorch/pytorch/commit/01be4d6b205be248b803e97f218f6755c3001d68#diff-144377a1316897e9ad9ff9d038b46db6L120) so it is not possibly to run the code with the latest PyTorch version.

**Comment by raulpuric** [comment]
Ahh yes sorry, the old version of pytorch we used had some bugs with dataparallel.
v0.3.0 seems to have fixed them though.
Tentatively updated code to work with the most recent version.
Leaving this open for now. Let me know if it worked for you.

**Comment by stefan-it** [comment]
`data_parallel.py` was removed with 806e542043c4aada028236c8928f917f9d855c5c, so I'm closing here :)
