### ISSUE TITLE
Minimal sentiment classification code

### ISSUE THREAD

**Issue by harsham05** [NVIDIA/sentiment-discovery#51]
I'm trying to expose the pre-trained models over REST, such that an HTTP POST request with a list of strings returns a response with their corresponding sentiment scores. The command line args can be replaced with their defaults.

I noticed that ```configure_data.py``` is being used to split the input data into train, test & validation batches & is also calling methods from ```data_utils``` module to prepare the data for training

https://github.com/NVIDIA/sentiment-discovery/blob/7f5ab28918a6fc29318a30f557b9454f0f5cc26a/classifier.py#L49

But, is there a simpler way to pass in a list of strings to the ```classify``` method?

https://github.com/NVIDIA/sentiment-discovery/blob/7f5ab28918a6fc29318a30f557b9454f0f5cc26a/classifier.py#L72

**Comment by tanmaypandey7** [comment]
Hi Harsham, were you able to find a way to do it?
