### ISSUE TITLE
undefined name 'output'

### ISSUE THREAD

**Issue by cclauss** [NVIDIA/sentiment-discovery#8]
flake8 testing of https://github.com/NVIDIA/sentiment-discovery on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./sentiment_discovery/model/sequence_model.py:219:35: F821 undefined name 'output'
					output = _output*dont_mask + output*(1 - dont_mask)
                                  ^
```

**Comment by raulpuric** [comment]
Hi, that's actually correct. output isn't defined until the first time step completes. We have the correct logic to check for this.
```
if t != 0:
    output = _output*dont_mask + output*(1 - dont_mask)
else:
    output = _output
```
